fragment PeopleParts on People {
  __typename
  people {
    __typename
    name
    type
    role
    start_year
    years_active
    photo
    linkedin
    durham_staff_link
    link
  }
}

fragment ResearchParts on Research {
  __typename
  papers {
    __typename
    title
    url
    thumbnail
    authors {
      __typename
      name
      team
    }
    year
    month
    venue
    tags
    type
  }
}

fragment SupportersParts on Supporters {
  __typename
  supporters {
    __typename
    name
    logo
    link
    subtitle
  }
}
