//@ts-nocheck
  // DO NOT MODIFY THIS FILE. This file is automatically generated by Tina
  export function gql(strings: TemplateStringsArray, ...args: string[]): string {
    let str = ''
    strings.forEach((string, i) => {
      str += string + (args[i] || '')
    })
    return str
  }
  export type Maybe<T> = T | null;
export type InputMaybe<T> = Maybe<T>;
export type Exact<T extends { [key: string]: unknown }> = { [K in keyof T]: T[K] };
export type MakeOptional<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]?: Maybe<T[SubKey]> };
export type MakeMaybe<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]: Maybe<T[SubKey]> };
export type MakeEmpty<T extends { [key: string]: unknown }, K extends keyof T> = { [_ in K]?: never };
export type Incremental<T> = T | { [P in keyof T]?: P extends ' $fragmentName' | '__typename' ? T[P] : never };
/** All built-in and custom scalars, mapped to their actual values */
export type Scalars = {
  ID: { input: string; output: string; }
  String: { input: string; output: string; }
  Boolean: { input: boolean; output: boolean; }
  Int: { input: number; output: number; }
  Float: { input: number; output: number; }
  /** References another document, used as a foreign key */
  Reference: { input: any; output: any; }
  JSON: { input: any; output: any; }
};

export type SystemInfo = {
  __typename?: 'SystemInfo';
  filename: Scalars['String']['output'];
  title?: Maybe<Scalars['String']['output']>;
  basename: Scalars['String']['output'];
  hasReferences?: Maybe<Scalars['Boolean']['output']>;
  breadcrumbs: Array<Scalars['String']['output']>;
  path: Scalars['String']['output'];
  relativePath: Scalars['String']['output'];
  extension: Scalars['String']['output'];
  template: Scalars['String']['output'];
  collection: Collection;
};


export type SystemInfoBreadcrumbsArgs = {
  excludeExtension?: InputMaybe<Scalars['Boolean']['input']>;
};

export type Folder = {
  __typename?: 'Folder';
  name: Scalars['String']['output'];
  path: Scalars['String']['output'];
};

export type PageInfo = {
  __typename?: 'PageInfo';
  hasPreviousPage: Scalars['Boolean']['output'];
  hasNextPage: Scalars['Boolean']['output'];
  startCursor: Scalars['String']['output'];
  endCursor: Scalars['String']['output'];
};

export type Node = {
  id: Scalars['ID']['output'];
};

export type Document = {
  id: Scalars['ID']['output'];
  _sys?: Maybe<SystemInfo>;
  _values: Scalars['JSON']['output'];
};

/** A relay-compliant pagination connection */
export type Connection = {
  totalCount: Scalars['Float']['output'];
  pageInfo: PageInfo;
};

export type Query = {
  __typename?: 'Query';
  getOptimizedQuery?: Maybe<Scalars['String']['output']>;
  collection: Collection;
  collections: Array<Collection>;
  node: Node;
  document: DocumentNode;
  people: People;
  peopleConnection: PeopleConnection;
  research: Research;
  researchConnection: ResearchConnection;
  supporters: Supporters;
  supportersConnection: SupportersConnection;
};


export type QueryGetOptimizedQueryArgs = {
  queryString: Scalars['String']['input'];
};


export type QueryCollectionArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
};


export type QueryNodeArgs = {
  id?: InputMaybe<Scalars['String']['input']>;
};


export type QueryDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryPeopleArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryPeopleConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<PeopleFilter>;
};


export type QueryResearchArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryResearchConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<ResearchFilter>;
};


export type QuerySupportersArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QuerySupportersConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<SupportersFilter>;
};

export type DocumentFilter = {
  people?: InputMaybe<PeopleFilter>;
  research?: InputMaybe<ResearchFilter>;
  supporters?: InputMaybe<SupportersFilter>;
};

export type DocumentConnectionEdges = {
  __typename?: 'DocumentConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<DocumentNode>;
};

export type DocumentConnection = Connection & {
  __typename?: 'DocumentConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<DocumentConnectionEdges>>>;
};

export type Collection = {
  __typename?: 'Collection';
  name: Scalars['String']['output'];
  slug: Scalars['String']['output'];
  label?: Maybe<Scalars['String']['output']>;
  path: Scalars['String']['output'];
  format?: Maybe<Scalars['String']['output']>;
  matches?: Maybe<Scalars['String']['output']>;
  templates?: Maybe<Array<Maybe<Scalars['JSON']['output']>>>;
  fields?: Maybe<Array<Maybe<Scalars['JSON']['output']>>>;
  documents: DocumentConnection;
};


export type CollectionDocumentsArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<DocumentFilter>;
  folder?: InputMaybe<Scalars['String']['input']>;
};

export type DocumentNode = People | Research | Supporters | Folder;

export type PeoplePeople = {
  __typename?: 'PeoplePeople';
  name: Scalars['String']['output'];
  type: Scalars['String']['output'];
  role: Scalars['String']['output'];
  start_year?: Maybe<Scalars['Float']['output']>;
  years_active?: Maybe<Scalars['String']['output']>;
  photo?: Maybe<Scalars['String']['output']>;
  linkedin?: Maybe<Scalars['String']['output']>;
  durham_staff_link?: Maybe<Scalars['String']['output']>;
  link?: Maybe<Scalars['String']['output']>;
};

export type People = Node & Document & {
  __typename?: 'People';
  people?: Maybe<Array<Maybe<PeoplePeople>>>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type StringFilter = {
  startsWith?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type NumberFilter = {
  lt?: InputMaybe<Scalars['Float']['input']>;
  lte?: InputMaybe<Scalars['Float']['input']>;
  gte?: InputMaybe<Scalars['Float']['input']>;
  gt?: InputMaybe<Scalars['Float']['input']>;
  eq?: InputMaybe<Scalars['Float']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['Float']['input']>>>;
};

export type ImageFilter = {
  startsWith?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type PeoplePeopleFilter = {
  name?: InputMaybe<StringFilter>;
  type?: InputMaybe<StringFilter>;
  role?: InputMaybe<StringFilter>;
  start_year?: InputMaybe<NumberFilter>;
  years_active?: InputMaybe<StringFilter>;
  photo?: InputMaybe<ImageFilter>;
  linkedin?: InputMaybe<StringFilter>;
  durham_staff_link?: InputMaybe<StringFilter>;
  link?: InputMaybe<StringFilter>;
};

export type PeopleFilter = {
  people?: InputMaybe<PeoplePeopleFilter>;
};

export type PeopleConnectionEdges = {
  __typename?: 'PeopleConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<People>;
};

export type PeopleConnection = Connection & {
  __typename?: 'PeopleConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<PeopleConnectionEdges>>>;
};

export type ResearchPapersAuthors = {
  __typename?: 'ResearchPapersAuthors';
  name: Scalars['String']['output'];
  team?: Maybe<Scalars['Boolean']['output']>;
};

export type ResearchPapers = {
  __typename?: 'ResearchPapers';
  title: Scalars['String']['output'];
  url: Scalars['String']['output'];
  thumbnail?: Maybe<Scalars['String']['output']>;
  authors?: Maybe<Array<Maybe<ResearchPapersAuthors>>>;
  year: Scalars['Float']['output'];
  month?: Maybe<Scalars['Float']['output']>;
  venue: Scalars['String']['output'];
  tags?: Maybe<Array<Maybe<Scalars['String']['output']>>>;
  type: Scalars['String']['output'];
};

export type Research = Node & Document & {
  __typename?: 'Research';
  papers?: Maybe<Array<Maybe<ResearchPapers>>>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type BooleanFilter = {
  eq?: InputMaybe<Scalars['Boolean']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
};

export type ResearchPapersAuthorsFilter = {
  name?: InputMaybe<StringFilter>;
  team?: InputMaybe<BooleanFilter>;
};

export type ResearchPapersFilter = {
  title?: InputMaybe<StringFilter>;
  url?: InputMaybe<StringFilter>;
  thumbnail?: InputMaybe<ImageFilter>;
  authors?: InputMaybe<ResearchPapersAuthorsFilter>;
  year?: InputMaybe<NumberFilter>;
  month?: InputMaybe<NumberFilter>;
  venue?: InputMaybe<StringFilter>;
  tags?: InputMaybe<StringFilter>;
  type?: InputMaybe<StringFilter>;
};

export type ResearchFilter = {
  papers?: InputMaybe<ResearchPapersFilter>;
};

export type ResearchConnectionEdges = {
  __typename?: 'ResearchConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Research>;
};

export type ResearchConnection = Connection & {
  __typename?: 'ResearchConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<ResearchConnectionEdges>>>;
};

export type SupportersSupporters = {
  __typename?: 'SupportersSupporters';
  name: Scalars['String']['output'];
  logo: Scalars['String']['output'];
  link: Scalars['String']['output'];
  subtitle?: Maybe<Scalars['String']['output']>;
};

export type Supporters = Node & Document & {
  __typename?: 'Supporters';
  supporters?: Maybe<Array<Maybe<SupportersSupporters>>>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type SupportersSupportersFilter = {
  name?: InputMaybe<StringFilter>;
  logo?: InputMaybe<StringFilter>;
  link?: InputMaybe<StringFilter>;
  subtitle?: InputMaybe<StringFilter>;
};

export type SupportersFilter = {
  supporters?: InputMaybe<SupportersSupportersFilter>;
};

export type SupportersConnectionEdges = {
  __typename?: 'SupportersConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Supporters>;
};

export type SupportersConnection = Connection & {
  __typename?: 'SupportersConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<SupportersConnectionEdges>>>;
};

export type Mutation = {
  __typename?: 'Mutation';
  addPendingDocument: DocumentNode;
  updateDocument: DocumentNode;
  deleteDocument: DocumentNode;
  createDocument: DocumentNode;
  createFolder: DocumentNode;
  updatePeople: People;
  createPeople: People;
  updateResearch: Research;
  createResearch: Research;
  updateSupporters: Supporters;
  createSupporters: Supporters;
};


export type MutationAddPendingDocumentArgs = {
  collection: Scalars['String']['input'];
  relativePath: Scalars['String']['input'];
  template?: InputMaybe<Scalars['String']['input']>;
};


export type MutationUpdateDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
  params: DocumentUpdateMutation;
};


export type MutationDeleteDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
};


export type MutationCreateDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
  params: DocumentMutation;
};


export type MutationCreateFolderArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
};


export type MutationUpdatePeopleArgs = {
  relativePath: Scalars['String']['input'];
  params: PeopleMutation;
};


export type MutationCreatePeopleArgs = {
  relativePath: Scalars['String']['input'];
  params: PeopleMutation;
};


export type MutationUpdateResearchArgs = {
  relativePath: Scalars['String']['input'];
  params: ResearchMutation;
};


export type MutationCreateResearchArgs = {
  relativePath: Scalars['String']['input'];
  params: ResearchMutation;
};


export type MutationUpdateSupportersArgs = {
  relativePath: Scalars['String']['input'];
  params: SupportersMutation;
};


export type MutationCreateSupportersArgs = {
  relativePath: Scalars['String']['input'];
  params: SupportersMutation;
};

export type DocumentUpdateMutation = {
  people?: InputMaybe<PeopleMutation>;
  research?: InputMaybe<ResearchMutation>;
  supporters?: InputMaybe<SupportersMutation>;
  relativePath?: InputMaybe<Scalars['String']['input']>;
};

export type DocumentMutation = {
  people?: InputMaybe<PeopleMutation>;
  research?: InputMaybe<ResearchMutation>;
  supporters?: InputMaybe<SupportersMutation>;
};

export type PeoplePeopleMutation = {
  name?: InputMaybe<Scalars['String']['input']>;
  type?: InputMaybe<Scalars['String']['input']>;
  role?: InputMaybe<Scalars['String']['input']>;
  start_year?: InputMaybe<Scalars['Float']['input']>;
  years_active?: InputMaybe<Scalars['String']['input']>;
  photo?: InputMaybe<Scalars['String']['input']>;
  linkedin?: InputMaybe<Scalars['String']['input']>;
  durham_staff_link?: InputMaybe<Scalars['String']['input']>;
  link?: InputMaybe<Scalars['String']['input']>;
};

export type PeopleMutation = {
  people?: InputMaybe<Array<InputMaybe<PeoplePeopleMutation>>>;
};

export type ResearchPapersAuthorsMutation = {
  name?: InputMaybe<Scalars['String']['input']>;
  team?: InputMaybe<Scalars['Boolean']['input']>;
};

export type ResearchPapersMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  url?: InputMaybe<Scalars['String']['input']>;
  thumbnail?: InputMaybe<Scalars['String']['input']>;
  authors?: InputMaybe<Array<InputMaybe<ResearchPapersAuthorsMutation>>>;
  year?: InputMaybe<Scalars['Float']['input']>;
  month?: InputMaybe<Scalars['Float']['input']>;
  venue?: InputMaybe<Scalars['String']['input']>;
  tags?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
  type?: InputMaybe<Scalars['String']['input']>;
};

export type ResearchMutation = {
  papers?: InputMaybe<Array<InputMaybe<ResearchPapersMutation>>>;
};

export type SupportersSupportersMutation = {
  name?: InputMaybe<Scalars['String']['input']>;
  logo?: InputMaybe<Scalars['String']['input']>;
  link?: InputMaybe<Scalars['String']['input']>;
  subtitle?: InputMaybe<Scalars['String']['input']>;
};

export type SupportersMutation = {
  supporters?: InputMaybe<Array<InputMaybe<SupportersSupportersMutation>>>;
};

export type PeoplePartsFragment = { __typename: 'People', people?: Array<{ __typename: 'PeoplePeople', name: string, type: string, role: string, start_year?: number | null, years_active?: string | null, photo?: string | null, linkedin?: string | null, durham_staff_link?: string | null, link?: string | null } | null> | null };

export type ResearchPartsFragment = { __typename: 'Research', papers?: Array<{ __typename: 'ResearchPapers', title: string, url: string, thumbnail?: string | null, year: number, month?: number | null, venue: string, tags?: Array<string | null> | null, type: string, authors?: Array<{ __typename: 'ResearchPapersAuthors', name: string, team?: boolean | null } | null> | null } | null> | null };

export type SupportersPartsFragment = { __typename: 'Supporters', supporters?: Array<{ __typename: 'SupportersSupporters', name: string, logo: string, link: string, subtitle?: string | null } | null> | null };

export type PeopleQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type PeopleQuery = { __typename?: 'Query', people: { __typename: 'People', id: string, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, people?: Array<{ __typename: 'PeoplePeople', name: string, type: string, role: string, start_year?: number | null, years_active?: string | null, photo?: string | null, linkedin?: string | null, durham_staff_link?: string | null, link?: string | null } | null> | null } };

export type PeopleConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<PeopleFilter>;
}>;


export type PeopleConnectionQuery = { __typename?: 'Query', peopleConnection: { __typename?: 'PeopleConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'PeopleConnectionEdges', cursor: string, node?: { __typename: 'People', id: string, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, people?: Array<{ __typename: 'PeoplePeople', name: string, type: string, role: string, start_year?: number | null, years_active?: string | null, photo?: string | null, linkedin?: string | null, durham_staff_link?: string | null, link?: string | null } | null> | null } | null } | null> | null } };

export type ResearchQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type ResearchQuery = { __typename?: 'Query', research: { __typename: 'Research', id: string, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, papers?: Array<{ __typename: 'ResearchPapers', title: string, url: string, thumbnail?: string | null, year: number, month?: number | null, venue: string, tags?: Array<string | null> | null, type: string, authors?: Array<{ __typename: 'ResearchPapersAuthors', name: string, team?: boolean | null } | null> | null } | null> | null } };

export type ResearchConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<ResearchFilter>;
}>;


export type ResearchConnectionQuery = { __typename?: 'Query', researchConnection: { __typename?: 'ResearchConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'ResearchConnectionEdges', cursor: string, node?: { __typename: 'Research', id: string, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, papers?: Array<{ __typename: 'ResearchPapers', title: string, url: string, thumbnail?: string | null, year: number, month?: number | null, venue: string, tags?: Array<string | null> | null, type: string, authors?: Array<{ __typename: 'ResearchPapersAuthors', name: string, team?: boolean | null } | null> | null } | null> | null } | null } | null> | null } };

export type SupportersQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type SupportersQuery = { __typename?: 'Query', supporters: { __typename: 'Supporters', id: string, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, supporters?: Array<{ __typename: 'SupportersSupporters', name: string, logo: string, link: string, subtitle?: string | null } | null> | null } };

export type SupportersConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<SupportersFilter>;
}>;


export type SupportersConnectionQuery = { __typename?: 'Query', supportersConnection: { __typename?: 'SupportersConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'SupportersConnectionEdges', cursor: string, node?: { __typename: 'Supporters', id: string, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, supporters?: Array<{ __typename: 'SupportersSupporters', name: string, logo: string, link: string, subtitle?: string | null } | null> | null } | null } | null> | null } };

export const PeoplePartsFragmentDoc = gql`
    fragment PeopleParts on People {
  __typename
  people {
    __typename
    name
    type
    role
    start_year
    years_active
    photo
    linkedin
    durham_staff_link
    link
  }
}
    `;
export const ResearchPartsFragmentDoc = gql`
    fragment ResearchParts on Research {
  __typename
  papers {
    __typename
    title
    url
    thumbnail
    authors {
      __typename
      name
      team
    }
    year
    month
    venue
    tags
    type
  }
}
    `;
export const SupportersPartsFragmentDoc = gql`
    fragment SupportersParts on Supporters {
  __typename
  supporters {
    __typename
    name
    logo
    link
    subtitle
  }
}
    `;
export const PeopleDocument = gql`
    query people($relativePath: String!) {
  people(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...PeopleParts
  }
}
    ${PeoplePartsFragmentDoc}`;
export const PeopleConnectionDocument = gql`
    query peopleConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: PeopleFilter) {
  peopleConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...PeopleParts
      }
    }
  }
}
    ${PeoplePartsFragmentDoc}`;
export const ResearchDocument = gql`
    query research($relativePath: String!) {
  research(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...ResearchParts
  }
}
    ${ResearchPartsFragmentDoc}`;
export const ResearchConnectionDocument = gql`
    query researchConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: ResearchFilter) {
  researchConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...ResearchParts
      }
    }
  }
}
    ${ResearchPartsFragmentDoc}`;
export const SupportersDocument = gql`
    query supporters($relativePath: String!) {
  supporters(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...SupportersParts
  }
}
    ${SupportersPartsFragmentDoc}`;
export const SupportersConnectionDocument = gql`
    query supportersConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: SupportersFilter) {
  supportersConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...SupportersParts
      }
    }
  }
}
    ${SupportersPartsFragmentDoc}`;
export type Requester<C= {}> = <R, V>(doc: DocumentNode, vars?: V, options?: C) => Promise<R>
  export function getSdk<C>(requester: Requester<C>) {
    return {
      people(variables: PeopleQueryVariables, options?: C): Promise<{data: PeopleQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: PeopleQueryVariables, query: string}> {
        return requester<{data: PeopleQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: PeopleQueryVariables, query: string}, PeopleQueryVariables>(PeopleDocument, variables, options);
      },
    peopleConnection(variables?: PeopleConnectionQueryVariables, options?: C): Promise<{data: PeopleConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: PeopleConnectionQueryVariables, query: string}> {
        return requester<{data: PeopleConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: PeopleConnectionQueryVariables, query: string}, PeopleConnectionQueryVariables>(PeopleConnectionDocument, variables, options);
      },
    research(variables: ResearchQueryVariables, options?: C): Promise<{data: ResearchQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ResearchQueryVariables, query: string}> {
        return requester<{data: ResearchQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ResearchQueryVariables, query: string}, ResearchQueryVariables>(ResearchDocument, variables, options);
      },
    researchConnection(variables?: ResearchConnectionQueryVariables, options?: C): Promise<{data: ResearchConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ResearchConnectionQueryVariables, query: string}> {
        return requester<{data: ResearchConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ResearchConnectionQueryVariables, query: string}, ResearchConnectionQueryVariables>(ResearchConnectionDocument, variables, options);
      },
    supporters(variables: SupportersQueryVariables, options?: C): Promise<{data: SupportersQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: SupportersQueryVariables, query: string}> {
        return requester<{data: SupportersQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: SupportersQueryVariables, query: string}, SupportersQueryVariables>(SupportersDocument, variables, options);
      },
    supportersConnection(variables?: SupportersConnectionQueryVariables, options?: C): Promise<{data: SupportersConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: SupportersConnectionQueryVariables, query: string}> {
        return requester<{data: SupportersConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: SupportersConnectionQueryVariables, query: string}, SupportersConnectionQueryVariables>(SupportersConnectionDocument, variables, options);
      }
    };
  }
  export type Sdk = ReturnType<typeof getSdk>;

// TinaSDK generated code
import { createClient, TinaClient } from "tinacms/dist/client";

const generateRequester = (
  client: TinaClient,
) => {
  const requester: (
    doc: any,
    vars?: any,
    options?: {
      branch?: string,
      /**
       * Aside from `method` and `body`, all fetch options are passed
       * through to underlying fetch request
       */
      fetchOptions?: Omit<Parameters<typeof fetch>[1], 'body' | 'method'>,
    },
    client
  ) => Promise<any> = async (doc, vars, options) => {
    let url = client.apiUrl
    if (options?.branch) {
      const index = client.apiUrl.lastIndexOf('/')
      url = client.apiUrl.substring(0, index + 1) + options.branch
    }
    const data = await client.request({
      query: doc,
      variables: vars,
      url,
    }, options)

    return { data: data?.data, errors: data?.errors, query: doc, variables: vars || {} }
  }

  return requester
}

/**
 * @experimental this class can be used but may change in the future
 **/
export const ExperimentalGetTinaClient = () =>
  getSdk(
    generateRequester(
      createClient({
        url: "https://content.tinajs.io/2.2/content/01b2869a-fc84-4ea6-8882-ca1054ada8f1/github/main",
        queries,
      })
    )
  )

export const queries = (
  client: TinaClient,
) => {
  const requester = generateRequester(client)
  return getSdk(requester)
}

  