# Durham AI Safety Initiative Website Configuration
# ==============================================

# Site Information
title: "Durham AI Safety Initiative"
description: >-
  Durham AI Safety Initiative (AISI) is a student-led organization at Durham University 
  dedicated to advancing AI safety research, education, and community engagement.

# Contact Information
email: durhamaisi@durham.ac.uk
baseurl: "" # Leave empty for GitHub Pages main domain
url: "https://durhamaisafety.github.io" # Your GitHub Pages URL (no trailing slash)
lang: en_GB

# Social Media Links
social:
  # Used by templates and jekyll-seo-tag JSON-LD (when name/links present)
  name: "Durham AI Safety Initiative"
  links:
    - "https://www.instagram.com/ais_durham"
    - "https://linktr.ee/aisdurham"
  # Convenience keys used elsewhere in templates
  instagram: "https://www.instagram.com/ais_durham"
  linktree: "https://linktr.ee/aisdurham"

# Repository Information (for edit links)
repository: "DurhamAISafety/durhamaisafety.github.io"
show_edit_link: false # Set to true to show "Edit this page" links

# SEO and Analytics
google_analytics: # Add your GA tracking ID here if needed
google_site_verification: BD22yCN98mhUEUuWtahSEQ18Jsti83oPb6WgG3LuCCw

# Build Settings
markdown: kramdown
highlighter: rouge
theme: minima
permalink: pretty
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Navigation (for automatic menu generation)
nav_pages:
  - title: "Home"
    url: "/"
  - title: "About Us"
    url: "/about/"
  - title: "Events"
    url: "/#events"

dropdown_pages:
  - title: "Our Team"
    url: "/our-team/"
  - title: "Programs"
    url: "/programs/"
  - title: "Research"
    url: "/research/"
  - title: "What is AI Safety?"
    url: "/what-is-ai-safety/"
  - title: "Get Involved"
    url: "/get-involved/"

# Content Collections
collections:
  research_projects:
    output: false
  events:
    output: false

# Default page settings
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
      image: "/images/AIS-logo.png"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      image: "/images/AIS-logo.png"

# Sass Configuration
sass:
  sass_dir: _sass
  style: compressed

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/
  - .bundle/
  - .git/
  - .gitignore
  - README.md
  - package.json
  - package-lock.json
  - gulpfile.js
  - .DS_Store
  - public/
  - src/
  - dist/
  - zany-zenith/

# Include hidden files/folders (if needed)
include:
  - .htaccess

# Timezone
timezone: Europe/London

# Pagination (if blog is added)
paginate: 10
paginate_path: "/blog/page:num/"

# SEO Plugin Settings
webmaster_verifications:
  google: BD22yCN98mhUEUuWtahSEQ18Jsti83oPb6WgG3LuCCw
  bing: # Bing Webmaster Tools verification code

# Site Author (for SEO)
author:
  name: "Durham AI Safety Initiative"
  email: "durhamaisi@durham.ac.uk"
  
# Organization Schema
organization:
  name: "Durham AI Safety Initiative"
  url: "https://durhamaisafety.github.io"
  logo: "https://durhamaisafety.github.io/images/AIS-logo.png"
  sameAs:
    - "https://www.instagram.com/ais_durham"
    - "https://linktr.ee/aisdurham"
# Site-wide logo used by jekyll-seo-tag
logo: "/images/AIS-logo.png"
# --------------
## Minima theme is enabled above via `theme: minima` and the required plugins
## are included in the `plugins` list already.


# Minima-specific settings (applicable to Minima v3 and above only)
# -----------------------------------------------------------------
#
#  *All described config keys below should be nested under the top-level
#   `minima` key.*
#
minima:
#   Minima skin selection. Available skins are:
#     * classic            Default, light color scheme.
#     * dark               Dark variant of the classic skin.
#     * auto               Adaptive skin based on the classic and dark skins.
#     * solarized-light    Light variant of solarized color scheme.
#     * solarized-dark     Dark variant of solarized color scheme.
#     * solarized          Adaptive skin for solarized color scheme skins.
  skin: auto
#
#   Specific pages for site navigation.
#     If you wish to link only specific pages in the site-navigation, use this
#     and list the `path` property (as represented via Liquid) of the pages in
#     the order they should be rendered.
#   nav_pages:
#     - about.md
#
#   Set to `true` to show excerpts on the homepage.
#   show_excerpts: false
#
#   Minima date format.
#     The default value is "%b %d, %Y" (e.g. Nov 14, 2023).
#     Refer to https://shopify.github.io/liquid/filters/date/ for valid values
#   date_format: "%b-%d-%Y"
#
#   Social Media Links.
#     Renders icons via Font Awesome Free webfonts CDN, based on ordered list of
#     entries. Valid entry keys:
#       * title    Tooltip rendered on hovering over icon.
#       * icon     Font Awesome icon id. `github` corresponds to `fa-github`.
#       * url      Full URL of social profile.
  social_links:
    - title: Minima Theme repository at GitHub
      icon: github
      url: "https://github.com/jekyll/minima"
#     - title: Jekyll at X (formerly Twitter)
#       icon: x-twitter
#       url: "https://x.com/jekyllrb"
#
#   Hide syndication feed subscription link.
#     RSS / Atom feed link is always rendered as the last item of social-links
#     list. Set below key to `true` to not have the link to feed rendered as
#     part of social-links list.
#   hide_site_feed_link: false
